<LoginScreen>:
    GridLeyout:
        GridLeyout:
            Label:
                text: "User Login"
            TextInput:
                hint_text: "Username"
            TextInput:
                hint_text: "Password"
            Button:
                text: "Login"
        GridLeyout:
            cols: 2
            Button:
                text: "Forgot Password?"
            Button:
                text: "Sign Up"

<RootWidget>:

